services:
  app:
    build:
      context: ./
      dockerfile: php-nginx.docker
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
      - main_nginx

  db:
    image: mysql:8.1
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
    volumes:
      - dbdata-adminpanel:/var/lib/mysql/
    networks:
      - app-network

networks:
  app-network:
  main_nginx:
    external:
      name: evilcorp
    driver: bridge

volumes:
  dbdata-adminpanel:










