version: '2'
services:
  nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        container_name: nginx-admin-panel    
        volumes:
            - ./:/var/www
        ports:
            - "9780:80"
        links:
            - php-fpm
  php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        container_name: php-fpm-p    
        volumes:
            - ./:/var/www
        links:
            - mysql
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
  mysql:
        image: mysql:5.7
        container_name: db-p
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=vet"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=admin_panel_db"
        ports:
            - "39780:3306"











